# TensorFlow 2.0

In [1]:
import tensorflow as tf

In [2]:
# verify that you are running tensorflow 2.X.X
print(tf.__version__)

2.8.0


In [3]:
hello = tf.constant("Hello")

In [4]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [5]:
tf.print(hello)

Hello


In [6]:
# create another tensor
world = tf.constant("World")

In [7]:
tf.print(world)

World


In [8]:
tf.print(hello+world)

HelloWorld


In [9]:
tf.print(hello+" "+world+"!")

Hello World!


In [10]:
a = tf.constant(10)

In [11]:
b=tf.constant(20)

In [12]:
a+b

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [13]:
print(a+b)

tf.Tensor(30, shape=(), dtype=int32)


In [14]:
tf.print(a+b)

30


In [15]:
myarr = tf.fill((5,5),5) # matrix [press shift+tab to view details]

In [16]:
tf.print(myarr)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [17]:
myarr.numpy()  # tensor as a numpy array

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [18]:
a = tf.constant([[4,5],[6,6]])

In [19]:
a.get_shape()

TensorShape([2, 2])

In [20]:
b = tf.constant([[0],
                [9]])

In [21]:
b.get_shape

<bound method _EagerTensorBase.get_shape of <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[0],
       [9]])>>

In [22]:
mytensor = tf.random.normal((4,4),mean=0, stddev=1.0)

In [23]:
tf.print(mytensor)

[[1.90139747 0.850661516 1.33314693 0.602493107]
 [-0.870463133 -3.03252816 0.176264599 -1.57239079]
 [-0.678644538 -0.819007754 -0.785844386 -0.762294948]
 [-0.43146 -0.0625649691 -1.41012 0.984089255]]


In [24]:
mytensor.dtype

tf.float32

### Eager Execution

#### verify if running eager execution

Eager execution is a fairly new addition to the tensorflow framework, thus we wish to check
if eager is eanbled or disabled.

In [25]:
if (tf.executing_eagerly()):
    print("Eager Execution is enabled ( running operations immediately)\n")
else:
    print("You are not running eager execution. TensorFlow version >== 2.0.0" \
         "has eager execution enabled by default.")

Eager Execution is enabled ( running operations immediately)



Turn eager execution off by running:

    from tensorflow.python.framework.ops import disable_eager_execution
    disable_eager_execution()

In [26]:
print(("Turn ON eager execution by running: \n\n{0}\n\nor upgrade" \
     "your tensorflow version by running: \n\n{1}").format(
    "tf.compat.v1.enable_eager_execution()","!pip install --upgrade tensorflow\n"\
"!pip install --upgrade tensorflow-gpu"))

Turn ON eager execution by running: 

tf.compat.v1.enable_eager_execution()

or upgradeyour tensorflow version by running: 

!pip install --upgrade tensorflow
!pip install --upgrade tensorflow-gpu


### Simple Operations

###### The basic operations in tensorflow

<b>Common Use</b>

 *   Making tensors -- tf.constant and tf.variable
 *   Concatenation of two tensors by tf.concat
 *  Making tensors by tf.zeros or tf.ones
 *  Reshape data by tf.reshape
 *   Casting tensors to other data types by tf.cast

In [27]:
# Making a constant tensor A, that does not change.
A = tf.constant([[4,3],
                [6,3],
                [9,8]])

In [28]:
tf.print(A)

[[4 3]
 [6 3]
 [9 8]]


In [29]:
A.numpy()

array([[4, 3],
       [6, 3],
       [9, 8]])

In [30]:
# making a variable tensor VA, which can change. Notice; it's variable.
VA = tf.Variable(([1,0],
                [4,7]))

#Making another tensor B
B = tf.constant([[4,4],
                [7,8],
                [9,9]])

In [31]:
tf.print(B)

[[4 4]
 [7 8]
 [9 9]]


In [32]:
tf.print(VA)

[[1 0]
 [4 7]]


In [33]:
type(VA)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [34]:
type(B)

tensorflow.python.framework.ops.EagerTensor

### Concatenation by tf.concat

In [35]:
# concatenate columns

AB_concatenated = tf.concat(values=[A,B], axis=1)

print(f"Adding B\'s columns to A:\n {AB_concatenated.numpy()}")

Adding B's columns to A:
 [[4 3 4 4]
 [6 3 7 8]
 [9 8 9 9]]


In [36]:
 # concatenate along rows
AB_concatenated = tf.concat(values=[A,B], axis=0)
print(f"Adding B\'s rows to A:\n{AB_concatenated.numpy()}")

Adding B's rows to A:
[[4 3]
 [6 3]
 [9 8]
 [4 4]
 [7 8]
 [9 9]]


### Making tensors by tf.zeros anf tf.ones

In [37]:
# Making a tensor filled with zeros, shape=[rows, columns]

tensor = tf.zeros(shape=[2,4], dtype=tf.int32)
print(f'Tensor full of zeros a sint32, 2 rows and 4 columns:\n{tensor.numpy()}')

Tensor full of zeros a sint32, 2 rows and 4 columns:
[[0 0 0 0]
 [0 0 0 0]]


In [38]:
# Making a tensor filled with ones, shape=[rows, columns]

tensor = tf.ones(shape=[4,5], dtype=tf.float32)
print(f'Tensor full of zeros a sint32, 4 rows and 5 columns:\n{tensor.numpy()}')

Tensor full of zeros a sint32, 4 rows and 5 columns:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Reshape data by tf.reshape

In [39]:
# Making a tensor for reshaping
tensor = tf.constant([[5,2,8],
                     [2,2,7],
                     [5,5,6],
                     [1,3,2]])

In [40]:
# reshaping the tensor into a shape of; shape =[rows, columns]
reshaped_tensor = tf.reshape(tensor = tensor, 
                            shape=[1,12])

In [41]:
print(f"Tensor Before reshape:\n {tensor.numpy()}")

print(f"Tensor After reshape:\n {reshaped_tensor.numpy()}")

Tensor Before reshape:
 [[5 2 8]
 [2 2 7]
 [5 5 6]
 [1 3 2]]
Tensor After reshape:
 [[5 2 8 2 2 7 5 5 6 1 3 2]]


### Casting tensors to other data types by tf.cast3

In [42]:
# Making a  tensor

tensor = tf.constant([[1.3,7.5,4.6],
                     [7.2, 1.3, 8.88],
                     [1.4, 7.5,9.34],
                     [8.1, 5.4, 4.66]],
                    dtype=tf.float32)

tensor_as_int = tf.cast(tensor, tf.int32)

In [43]:
print(f"Tensor with floats: \n {tensor.numpy()}")

print(f"\n Tensor cast from float to  int (just remove the decimal, no rounding):\n{tensor_as_int.numpy()}")

Tensor with floats: 
 [[1.3  7.5  4.6 ]
 [7.2  1.3  8.88]
 [1.4  7.5  9.34]
 [8.1  5.4  4.66]]

 Tensor cast from float to  int (just remove the decimal, no rounding):
[[1 7 4]
 [7 1 8]
 [1 7 9]
 [8 5 4]]


### The Linera Algebra Operations

*    Transpose tensor
*    Matrix Multiplication
*    Element-wise multiplication
*    Identity Matrix

#### Transpose Matrix

In [44]:
# Some Matrix A
A = tf.constant([[9,7,6],
                [1,5,7]])
A = tf.transpose(A)

print(f'The Transposed matrix is: \n{A}')

The Transposed matrix is: 
[[9 1]
 [7 5]
 [6 7]]


#### Matrix Multiplication

In [45]:
# Some matrix A
A = tf.constant([[3,7],
                [1,9]])

# Some vector v
v  = tf.constant([[7],
                 [4]])

# Matrix multiplication
Av = tf.matmul(A, v)

print(f'Matrix multiplication of A na d v results in a new tensor: \n {Av}')

Matrix multiplication of A na d v results in a new tensor: 
 [[49]
 [43]]


#### Elemt-wise multiplication

Comparing matrix multiplication and elementwise multiplication. We can see that
they are actually different.

In [46]:
# Elemtwise multiplication

Av = tf.multiply(A, v)

print(f'The element-wise multiplication of A nad v results in a new tensor \n {Av}')

The element-wise multiplication of A nad v results in a new tensor 
 [[21 49]
 [ 4 36]]


#### Identity Matrix

In [47]:
# Some Matrix A

A = tf.constant([[3,7],
                [1,9]])

In [48]:
A.shape

TensorShape([2, 2])

In [49]:
# Get number of dimensions

rows, columns= A.shape
print(f'Number of rows in tensor A  is: {rows}')
print(f'Number of columns in tensor A is: {columns}')

Number of rows in tensor A  is: 2
Number of columns in tensor A is: 2


In [50]:
# Making identity MAtrix

A_identity = tf.eye(num_rows=rows,
                   num_columns=columns,
                   dtype=tf.int32)

print(f'\n The identity matrix of A: \n {A_identity.numpy()}')


 The identity matrix of A: 
 [[1 0]
 [0 1]]


In [51]:
# MAtrix multiplictaion of A.A_identity

AAt = tf.matmul(A, A_identity)

print(f'Matrix multipliaction of A and v results in a new tensor: \n {AAt}')

Matrix multipliaction of A and v results in a new tensor: 
 [[3 7]
 [1 9]]


#### Creating a variable in Tensorflow 2.0

To use the value of a  tf.Varaible in a tensorflow graph, simply traet it like anormal tf.tensor

In [52]:
# Create a variable
my_variable = tf.Variable(tf.zeros([2, 3, 4]))

In [53]:
tf.print(my_variable)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [54]:
v = tf.Variable(0.0)

w = v+1  # w is a tf.tensor ehich is computed based on value of v.

In [55]:
tf.print(v)
tf.print(w)

0
1


In [56]:
# assign

v = tf.Variable(0.0)
v.assign(2)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=2.0>

In [57]:
tf.print(v)

2


In [58]:
v = tf.Variable(0.0)

v.assign_add(1)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=1.0>

In [59]:
tf.print(v)

1


## Operations in TensorFlow 2.0

#### Functions, not sessions

#### Tensorflow 1.x

outputs = session.run(placeholder), feed_dict = {placeholdr, input}

#### TensorFlow 2.0

outputs = f(input)

In [60]:
def add_op(a,b):
    return a+b

In [61]:
print(add_op(10,20))

30


In [62]:
tf.print(add_op(tf.constant(10), tf.constant(20)))

30


In [63]:
# linear Model

w= tf.Variable([10], tf.int32)
b = tf.Variable([5], tf.int32)

In [64]:
def linear_model(x):
    return w*x+b

In [65]:
linear_model(x=[5,10,15,20]).numpy()

array([ 55, 105, 155, 205])

In [66]:
linear_model([5,10,2]).numpy()

array([ 55, 105,  25])