#### API Hierarchy

<img src="https://www.researchgate.net/profile/Abu-Kamruzzaman/publication/332540618/figure/fig5/AS:776663918985226@1562182516650/Tensor-Flow-API-Hierarchy-19.ppm"/>

In [1]:
# import tensorflow
import tensorflow as tf

In [2]:
print(tf.__version__)

2.8.0


In [3]:
x = tf.constant(
    [[3,5,7],
    [4,6,8]])

In [4]:
tf.print(x)

[[3 5 7]
 [4 6 8]]


In [5]:
# check type of x
type(x)

tensorflow.python.framework.ops.EagerTensor

In [6]:
#Slice
y=x[:,1]
y

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6])>

In [7]:
tf.print(y)

[5 6]


In [8]:
# reshape
y = tf.reshape(x, [3,2])  #reshapinf occurs row-wise (1st row, then 2nd row, then 3rd row, and so on.)
tf.print("x is: \n",x)
tf.print(f'reshape form of x is: \n{y}')

x is: 
 [[3 5 7]
 [4 6 8]]
reshape form of x is: 
[[3 5]
 [7 4]
 [6 8]]


A variable is a tensor whose value can be changed.

In [9]:
# x <- 2
x = tf.Variable(2.0, dtype=tf.float32, name='my_variable')
tf.print(x)

2


In [10]:
# Assign x to 48.5
# x <- 48.5

x.assign(48.5)
tf.print(x)

48.5


In [11]:
# x <- x+4
x.assign_add(4)
tf.print(x)

52.5


In [12]:
# x <- x-4
x.assign_sub(4)
tf.print(x)

48.5


In [13]:
x = tf.constant(
    [[3,5,7],
    [4,6,8]])
tf.print(x.shape, y.shape)

TensorShape([2, 3]) TensorShape([3, 2])


In [14]:
# matrix -multiplication
tf.print(tf.matmul(x,y))

[[86 91]
 [102 108]]


Tensorflow can compute the derivative of a function with respect to any parameter.
* the computation is recorded with <b> gradient tape</b>
* the function is expressed with <b> TensorFlow ops only!</b>

###### Gradient Tape records operations for Automatic Differentiation

In [15]:
def compute__gradients(X, Y, W0, W1):
    with tf.GradientTape as tape:
        loss = loss_mse(X, Y, W0, W1)
    return tape.gradient(loss, [W0, W1])

In [16]:
w0 = tf.Variable(0.0)
w1 = tf.Variable(0.0)

In [17]:
# import numpy
import numpy as np

In [18]:
# check tensorflow version
print("TensorFlow version: ",tf.version.VERSION)

TensorFlow version:  2.8.0


Tensors may have more axes, here is a tensor with 3-axes:

In [19]:
tensor_= tf.zeros([2, 3, 4])
print(tensor_)

tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(2, 3, 4), dtype=float32)


Convert a tensor into a NumPy array either using **np.array** or the **tensor.numpy** method:

In [20]:
# using np.array(tensor_)
np.array(tensor_)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)

In [21]:
#using tensor_.numpy()
tensor_.numpy()

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)

Tensors often contain floats and ints, but have many other types, including:

* complex numbers
* strings

Basic math operations on tensors, **addition**, **element-wise multiplication**, and **matrix multiplication**.

In [22]:
a = tf.constant([[3,7],
                [1,9]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2])`

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[ 4  8]
 [ 2 10]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 7]
 [1 9]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[10 10]
 [10 10]], shape=(2, 2), dtype=int32) 



Symbolically, mathematical operations can be performed as:

In [23]:
# element-wise addition
print(f"element-wise addition: {a + b}", "\n") 

# element-wise multiplication
print(f"element-wise multiplication: {a * b}", "\n") 

# matrix multiplication
print(f"matrix multiplication is: {a @ b}", "\n") 

element-wise addition: [[ 4  8]
 [ 2 10]] 

element-wise multiplication: [[3 7]
 [1 9]] 

matrix multiplication is: [[10 10]
 [10 10]] 



In [24]:
# find maximum value of tensor"a"
print(tf.reduce_max(a))

tf.Tensor(9, shape=(), dtype=int32)


In [25]:
# find smallest value
tf.print(tf.reduce_min(a))

1


In [26]:
# find index of minimum value
tf.print(f"a is: {a}")
tf.print(tf.argmax(a))

a is: [[3 7]
 [1 9]]
[0 1]


In [27]:
print(tf.argmax(a, axis=1))

tf.Tensor([1 1], shape=(2,), dtype=int64)


In [28]:
# find index value of minimum value along axis-0
tf.print("a is: ",a)
tf.print("\n index-position of smallest value alnog axis-0 is: ",tf.argmin(a, axis=0))

a is:  [[3 7]
 [1 9]]

 index-position of smallest value alnog axis-0 is:  [1 0]


In [29]:
# compute the softmax value of a along any particular axis
tf.print(tf.nn.softmax(tf.cast(a, tf.float32), axis=1, ))  # value inside "a" should not be 'int'.
# cast-data type

[[0.0179862101 0.982013762]
 [0.000335350138 0.999664664]]


In [30]:
# softmax along axis-0
tf.print(tf.nn.softmax(tf.cast(a, tf.float32), axis=0, ))

[[0.880797 0.119202912]
 [0.119202912 0.880797]]


Tensors have shapes.  Some terms are:

* **Shape**: The length (number of elements) of each of the dimensions of a tensor.
* **Rank**: Number of tensor dimensions.  A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
* **Axis** or **Dimension**: A particular dimension of a tensor.
* **Size**: The total number of items in the tensor, the product shape vector


In [31]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])

In [32]:
tf.print(f"rank_4_tensor is:\n {rank_4_tensor}")

rank_4_tensor is:
 [[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]


In [33]:
print("Data type of every element is:", rank_4_tensor.dtype)
print("Number of dimensions:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())  # calculate size (total_no. of terms)

Data type of every element is: <dtype: 'float32'>
Number of dimensions: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


In [34]:
# access particular elemennt
print(f"a is: \n{a}")

print(f"first element of a is: {a[0][0]}")
print(f"first row of a is : {a[0]}")
print(f"last element of a is: {a[-1][-1]}")

a is: 
[[3 7]
 [1 9]]
first element of a is: 3
first row of a is : [3 7]
last element of a is: 9


In [35]:
# slicing
print(f"last row of a is: {a[-1,:]}")

last row of a is: [1 9]


Manipulating Shapes **tf.reshape()**

In [36]:
var_x = tf.Variable(tf.constant([[1], [2], [3]]))
tf.print(f"var_x is: \n{var_x}")
tf.print(f"shape of var_x is: {var_x.shape}")

var_x is: 
<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[1],
       [2],
       [3]])>
shape of var_x is: (3, 1)


**.as_list()**

In [37]:
#Convert this object into a Python list, too
print(var_x.shape.as_list())

[3, 1]


In [38]:
# reshape into a new shape
x_reshaped = tf.reshape(var_x, [1, 3])

print(f"shape of actual x is: {var_x.shape}")
print(f"shape of reshaped_x is: {x_reshaped.shape}")

shape of actual x is: (3, 1)
shape of reshaped_x is: (1, 3)


TensorFlow uses C-style "row-major" memory ordering, where incrementing the right-most index corresponds to a single step in memory.

In [39]:
# Flattening a tensor
print(f"a is: \n{a}")
print(f" \nflattened form of a is: \n{tf.reshape(a,[-1])}")  # it's row-wise flattening in tensor.
#If you flatten a tensor you can see what order it is laid out in memory.

a is: 
[[3 7]
 [1 9]]
 
flattened form of a is: 
[3 7 1 9]


In [40]:
tf.reshape(a,[4,-1])

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[3],
       [7],
       [1],
       [9]])>

In [41]:
# This doesn't work at all
try:
  tf.reshape(a, [7, -1])
except Exception as e: print(e)


Input to reshape is a tensor with 4 values, but the requested shape requires a multiple of 7 [Op:Reshape]


###### Broadcasting

It is equivalent to numpy.

The simplest and most common case is when you attempt to multiply or add a tensor to a scalar. In that case, the scalar is broadcast to be the same shape as the other argument.

In [42]:
x = tf.constant([1, 2, 3])

y = tf.constant(2)
z = tf.constant([2, 2, 2])
# All of these are the same computation
print(tf.multiply(x, 2))
print(x * y)
print(x * z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [43]:
# These are the same computations
x = tf.reshape(x,[3,1])
y = tf.range(1, 5)  # tensorflow range() function.
print(x, "\n")
print(y, "\n")
print(tf.multiply(x, y))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


broadcasting looks like using **tf.broadcast_to.**

In [44]:
print(tf.broadcast_to(tf.constant([1, 2, 3]), [3, 3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


##### tf.convert_to_tensor

In [45]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

A tensor with variable numbers of elements along some axis is called "ragged". Use tf.ragged.RaggedTensor for ragged data.

For example, This cannot be represented as a regular tensor:

In [46]:
try:
  tensor = tf.constant(ragged_list)
except Exception as e: print(e)


Can't convert non-rectangular Python sequence to Tensor.


Instead create a **tf.RaggedTensor** using **tf.ragged.constant:**

In [47]:
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


In [48]:
# The shape of a tf.RaggedTensor contains unknown dimensions:

print(ragged_tensor.shape)

(4, None)


### String tensors

tf.string

In [49]:
# Tensors can be strings, too here is a scalar string.
scalar_string_tensor = tf.constant("Gray wolf")
print(scalar_string_tensor)

tf.Tensor(b'Gray wolf', shape=(), dtype=string)


In [50]:
# If we have two string tensors of different lengths, this is OK.
tensor_of_strings = tf.constant(["Gray wolf",
                                 "Quick brown fox",
                                 "Lazy dog"])

# shape is (3,), indicating that it is 3 x unknown.
print(tensor_of_strings)

tf.Tensor([b'Gray wolf' b'Quick brown fox' b'Lazy dog'], shape=(3,), dtype=string)


In the above printout the `b` prefix indicates that `tf.string` dtype is not a unicode string, but a byte-string. See the [Unicode Tutorial](https://www.tensorflow.org/tutorials/load_data/unicode) for more about working with unicode text in TensorFlow.

unicode characters are utf-8 encoded.

In [51]:
# We can use split to split a string into a set of tensors

print(tf.strings.split(scalar_string_tensor, sep=" "))

tf.Tensor([b'Gray' b'wolf'], shape=(2,), dtype=string)


In [52]:
help(tf.strings.split)

Help on function string_split_v2 in module tensorflow.python.ops.ragged.ragged_string_ops:

string_split_v2(input, sep=None, maxsplit=-1, name=None)
    Split elements of `input` based on `sep` into a `RaggedTensor`.
    
    Let N be the size of `input` (typically N will be the batch size). Split each
    element of `input` based on `sep` and return a `RaggedTensor` containing the
    split tokens. Empty tokens are ignored.
    
    Example:
    
    >>> tf.strings.split('hello world').numpy()
     array([b'hello', b'world'], dtype=object)
    >>> tf.strings.split(['hello world', 'a b c'])
    <tf.RaggedTensor [[b'hello', b'world'], [b'a', b'b', b'c']]>
    
    If `sep` is given, consecutive delimiters are not grouped together and are
    deemed to delimit empty strings. For example, `input` of `"1<>2<><>3"` and
    `sep` of `"<>"` returns `["1", "2", "", "3"]`. If `sep` is None or an empty
    string, consecutive whitespace are regarded as a single separator, and the
    result will

**Operations for working with string Tensors.**

Functions

**as_string(...):** Converts each entry in the given tensor to strings.

**bytes_split(...):** Split string elements of input into bytes.

**format(...):** Formats a string template using a list of tensors.

**join(...):** Perform element-wise concatenation of a list of string tensors.

**length(...):** String lengths of input.

**lower(...):** Converts all uppercase characters into their respective lowercase replacements.

**ngrams(...):** Create a tensor of n-grams based on data.

**reduce_join(...):** Joins all strings into a single string, or joins along an axis.

**regex_full_match(...):** Check if the input matches the regex pattern.

**regex_replace(...):** Replace elements of input matching regex pattern with rewrite.

**split(...):** Split elements of input based on sep into a RaggedTensor.

**strip(...):** Strip leading and trailing whitespaces from the Tensor.

**substr(...):** Return substrings from Tensor of strings.

**to_number(...):** Converts each string in the input Tensor to the specified numeric type.

**unicode_encode(...):** Encodes each sequence of Unicode code points in input into a string.

**unicode_split(...):** Splits each string in input into a sequence of Unicode code points.

**unsorted_segment_join(...):** Joins the elements of inputs based on segment_ids.

**upper(...):** Converts all lowercase characters into their respective uppercase replacements.

In [53]:
# it turns into a `RaggedTensor` if we split up a tensor of strings,
# as each string might be split into a different number of parts.

print(tf.strings.split(tensor_of_strings))

<tf.RaggedTensor [[b'Gray', b'wolf'], [b'Quick', b'brown', b'fox'], [b'Lazy', b'dog']]>


now, convert string-formed number into numeric value

**tf.strings.to_number()**

In [54]:
num_text = tf.constant("1 10 100")

print(tf.strings.to_number(tf.strings.split(num_text, " ")))

tf.Tensor([  1.  10. 100.], shape=(3,), dtype=float32)


In [55]:
try:
    print(tf.strings.to_number("1 10 100"))
except Exception as e:
    print(e)

StringToNumberOp could not correctly convert string: 1 10 100 [Op:StringToNumber]


**tf.cast()**

In [56]:
# convert it into bytes, and then into numbers

In [57]:
byte_strings = tf.strings.bytes_split(tf.constant("Duck"))
print("type of byte_strings is: ",type(byte_strings))
print("\n")

byte_ints = tf.io.decode_raw(tf.constant("Duck"), tf.uint8)
print("type of byte_ints is: ",type(byte_ints))
print("\n")

print("Byte strings:", byte_strings)

print("Bytes:", byte_ints)

type of byte_strings is:  <class 'tensorflow.python.framework.ops.EagerTensor'>


type of byte_ints is:  <class 'tensorflow.python.framework.ops.EagerTensor'>


Byte strings: tf.Tensor([b'D' b'u' b'c' b'k'], shape=(4,), dtype=string)
Bytes: tf.Tensor([ 68 117  99 107], shape=(4,), dtype=uint8)


In [58]:
# Or split it up as unicode and then decode it

unicode_bytes = tf.constant("Shayan")
unicode_char_bytes = tf.strings.unicode_split(unicode_bytes, "UTF-8")
unicode_values = tf.strings.unicode_decode(unicode_bytes, "UTF-8")

print("\nUnicode bytes:", unicode_bytes)
print("\nUnicode chars:", unicode_char_bytes)
print("\nUnicode values:", unicode_values)


Unicode bytes: tf.Tensor(b'Shayan', shape=(), dtype=string)

Unicode chars: tf.Tensor([b'S' b'h' b'a' b'y' b'a' b'n'], shape=(6,), dtype=string)

Unicode values: tf.Tensor([ 83 104  97 121  97 110], shape=(6,), dtype=int32)


The tf.string dtype is used for all raw bytes data in TensorFlow. The tf.io module contains functions for converting data to and from bytes, including decoding images and parsing csv.